### ISSUE TITLE
DeepstackException: Error from Deepstack: Detection endpoint not activated

### ISSUE THREAD

**Issue by Kouwe-sudo** [robmarkcole/deepstack-ui#17]
I don't think that the error itself is the issue. I think I am the issue myself but still I can't figure out where things go wrong in the above mentioned error (DeepstackException: Error from Deepstack: Detection endpoint not activated). Is it because I don't have an API? I use 'mysecretAPI'only because I don't know where to get one.

**Comment by robmarkcole** [comment]
Please use the `deepquestai/deepstack:gpu-x3-beta` image, I will update the readme
