### ISSUE TITLE
Connection error: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

### ISSUE THREAD

**Issue by Kouwe-sudo** [robmarkcole/deepstack-ui#18]
Again this might also be no real issue but due to my lack of knowledge but this is what I get on other occasions when I try to upload a picture for testing.

Connection error: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

**Comment by robmarkcole** [comment]
My guess is that this could be do to uploading a large image?

**Comment by robmarkcole** [comment]
No response, closing
