### ISSUE TITLE
Change port from 5000 to 80?

### ISSUE THREAD

**Issue by clandestine-avocado** [robmarkcole/deepstack-ui#24]
My Deepstack instance is accessible via port 80, and the UI Tool (which looks awesome!) is looking at 5000 - so I can load the tool, but get a connection error.

I run Deepstack in Docker with this command - thought I do not fully undestand the `80:5000` portion - only that it works via 80, but not 5000.

`sudo docker run -e VISION-SCENE=True -v localstorage:/datastore -p 80:5000 deepquestai/deepstack`

**Comment by robmarkcole** [comment]
the port is picked up from an environment variable: `DEEPSTACK_PORT = os.getenv("DEEPSTACK_PORT", 5000)`

I should probably document this but it then requires maintainence. Are you interested in opening a PR on the doc?

**Comment by robmarkcole** [comment]
Replaced by https://github.com/robmarkcole/deepstack-ui/issues/27
