### ISSUE TITLE
Add Time taken to process.

### ISSUE THREAD

**Issue by LucidityCrash** [robmarkcole/deepstack-ui#29]
Would it be possible to add some information about how long it took to process the image ?

**Comment by robmarkcole** [comment]
Why would you need to see this in the UI if it is in the Deepstack log? 
I am not saying no to this suggestion, I just want a good reason to justify it

**Comment by LucidityCrash** [comment]
You can do what this UI does with a couple of lines of python essentially its all just about conveniece and accessability (especially to the non technical) ... not that this is an especially good reason though :)
Also there seems to be a way to add your own training models now and being able to easily see the time and accuracy effects your own custom models have all in one place would be quite cool.

**Comment by robmarkcole** [comment]
@LucidityCrash checkout https://github.com/robmarkcole/deepstack-analytics/blob/master/speedtest.ipynb

I don't think I will be adding this feature to the deepstack-ui as this is more appropriate to the monitoring dashboard on https://github.com/johnolafenwa/DeepStack/issues/35

**Comment by LucidityCrash** [comment]
I love the speedtest and the monitoring dashboard idea, and agree that is a better place to put it.

**Comment by robmarkcole** [comment]
resolved
