### ISSUE TITLE
Always shows "Bad url supplied, url http://x.x.x.x:xxxx/v1/vision/custom/mask raised error 404"

### ISSUE THREAD

**Issue by kalyan427** [robmarkcole/deepstack-ui#49]
1. Tried with AmberPro docker. I can able to install and run the container and I have defined the environmental variable as you defined but I am always getting this error.
![Screen Shot 2021-01-28 at 2 40 21 PM](https://user-images.githubusercontent.com/9591600/106208210-e2dbf300-6177-11eb-9288-e614cea8524e.png)

**Comment by robmarkcole** [comment]
thats the ip and port of your deepstack instance. I suggest you use the docker-compose, or the network IP of your machine with deepstack on it

**Comment by jualfoar** [comment]
in order to make it work i had to comment the follow:
      #- DEEPSTACK_CUSTOM_MODEL=fire
See yaa.
