### ISSUE TITLE
Shows DeepStack Connection Error

### ISSUE THREAD

**Issue by kalyan427** [robmarkcole/deepstack-ui#50]
Hi always getting the below screenshot error. any suggestions will helpful. thanks.

![Screen Shot 2021-02-04 at 3 41 07 PM](https://user-images.githubusercontent.com/9591600/106969437-abcd8a80-66ff-11eb-90f4-e10ce72ebe15.png)

**Comment by 7thstorm** [comment]
having the same issue

**Comment by robmarkcole** [comment]
this has been raised before, please check closed issues before opening a new one, thanks

https://github.com/robmarkcole/deepstack-ui/issues/49
