### ISSUE TITLE
Unable to start UI  .. permission denied

### ISSUE THREAD

**Issue by 7thstorm** [robmarkcole/deepstack-ui#52]
I installed using the instructions.
When I verify:
`$sudo docker pull robmarkcole/deepstack-ui:latest
latest: Pulling from robmarkcole/deepstack-ui
Digest: sha256:864ea8a9812ca9e917147e75c8d22a0824a2111f3f5c6aa15312c5b3d43607b5
Status: Image is up to date for robmarkcole/deepstack-ui:latest
docker.io/robmarkcole/deepstack-ui:latest`

However, when I try to run it, I'm getting permission denied

`$sudo docker run -p 8501:8501 -e DEEPSTACK_IP='172.16.41.253' -e DEEPSTACK_PORT=777 deepstack-ui
Unable to find image 'deepstack-ui:latest' locally
docker: Error response from daemon: pull access denied for deepstack-ui, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

what am I missing

**Comment by robmarkcole** [comment]
this is docker question that can be resolved using google, see `repository does not exist or may require 'docker login'`
