### ISSUE TITLE
Docker build fails on Apple M1

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/deepstack-ui#56]
Fails with `#9 118.3 ERROR: Could not build wheels for pyarrow which use PEP 517 and cannot be installed directly`

The solution is to use emulation? `--platform linux/amd64`

**Comment by robmarkcole** [comment]
```
docker build -t deepstack-ui . --platform linux/amd64

```

**Comment by robmarkcole** [comment]
Just tested, no longer an issue

**Comment by berezerker** [comment]
The issues is still present.

**Comment by nschenone** [comment]
Issue is still present. Please see https://github.com/streamlit/streamlit/issues/4842
