### ISSUE TITLE
Issue with gettign ha to talk to ds error 401

### ISSUE THREAD

**Issue by Techknowledgeman** [robmarkcole/deepstack-ui#57]
Deepstack error : Error from Deepstack request, status code: 401.

`Logger: custom_components.deepstack_object.image_processing
Source: custom_components/deepstack_object/image_processing.py:352
Integration: deepstack_object (documentation)
First occurred: 18:23:45 (1 occurrences)
Last logged: 18:23:45

Deepstack error : Error from Deepstack request, status code: 401`

`image_processing:
  - platform: deepstack_object
    ip_address: 192.168.x.x
    port: 5000
    api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    scan_interval: 5
    save_file_folder: /config/snapshots/
    save_file_format: png
    save_timestamped_file: True
    always_save_latest_file: True
    targets:
      - target: person
      - target: car
    source:
      - entity_id: camera.frontyard
        name: frontyard_person_detection`

Deepstack UI works perfectly and I've double-checked the api_ky and used both this guid and also a password style api key.

**Comment by Techknowledgeman** [comment]
actually, hold off, I think I may have solved it. Just testing without api keys now

**Comment by robmarkcole** [comment]
no api key required in latest deepstack
