### ISSUE TITLE
Deepstack connection error and JSON Decode Error

### ISSUE THREAD

**Issue by DivanX10** [robmarkcole/deepstack-ui#59]
**Docker is installed on Synology. Installed the latest version of the Deepstack UI.**
Докер установлен на Synology. Установил последнюю версию Deepstack UI.

**deepstack doesn't work, I can't upload an image. If you install the image as is and enable the bridge, do not change the ports, then I will get this error**
не работает deepstack, не могу загрузить изображение. Если установить образ как есть и включить мост, не менять порты, то я получу такую ошибку 
![Deepstack UI](https://user-images.githubusercontent.com/64090632/116485556-3273ad00-a894-11eb-8f3e-c752aa1bd1ec.JPG)

-----------------------------
**If I still change the ports and do not include the bridge, I will get this error**
Если все же поменяю порты и не буду включать мост, то получу такую ошибку
![docker](https://user-images.githubusercontent.com/64090632/116485562-369fca80-a894-11eb-8928-d8b6efab4f29.JPG)
![docker02](https://user-images.githubusercontent.com/64090632/116485558-343d7080-a894-11eb-9f2f-52acf24d1f90.JPG)

**Comment by robmarkcole** [comment]
Suggest use the machine IP rather than localhost

**Comment by DivanX10** [comment]
**Thank you for answering**
Спасибо, что  ответили

**I do not use localhost, but specify the ip address. I thought maybe this is a problem with Synology. I tried to install it in the Home Assistant Portainer for the test, and ran it there. The problem is the same, I can't register the image and I also can't use the deepstack-ui.**

Я не использую localhost, а указываю ip адрес. Я думал, может это проблема у Synology. Попробовал для теста установить в Home Assistant Portainer, запустил там. Проблема та же, не могу зарегистрировать изображение и также не могу использовать deepstack-ui. 

![portainer - deepstack-ui](https://user-images.githubusercontent.com/64090632/116579325-f3d50580-a91a-11eb-8b54-410c40e58651.jpg)
![portainer - deepstack-ui 02](https://user-images.githubusercontent.com/64090632/116580170-c76db900-a91b-11eb-9adf-bc95b8245e5f.JPG)
![portainer - deepstack-ui 04](https://user-images.githubusercontent.com/64090632/116581192-bf624900-a91c-11eb-9008-c95e8bd92254.JPG)
![portainer - deepstack-ui 05](https://user-images.githubusercontent.com/64090632/116581201-c25d3980-a91c-11eb-9be8-a9599014b701.JPG)


![portainer - deepstack-ui 03](https://user-images.githubusercontent.com/64090632/116580182-ca68a980-a91b-11eb-85de-bfc12475e0fd.JPG)


**Also can't register an image via deepquestai/deepstack**
Также не могу зарегистрировать изображение через deepquestai/deepstack
**I tried it with quotation marks**
Пробовал с кавычками
```
service: image_processing.deepstack_teach_face
name: "Divan"
file_path: "/config/www/faces/divan/divan_01.jpg"
```

**I tried it without quotes**
Пробовал без кавычек
```
service: image_processing.deepstack_teach_face
name: Divan
file_path: /config/www/faces/divan/divan_01.jpg
```


**The logs report this**
В логах сообщается про это
`Error handling message: extra keys not allowed @ data['sequence'][0]['file_path']. Got '/config/www/faces/divan/divan_01.jpg' extra keys not allowed @ data['sequence'][0]['name']. Got 'Divan'`

**Comment by robmarkcole** [comment]
It appears your ran deepstack-ui without the required environment variables for the deepstack instance - I can see `localhost` in the error, which is the default

**Comment by DivanX10** [comment]
**Maybe I'm setting it up incorrectly or I need some library for the deepstack-ui to work?**
Может я неправильно настраиваю или нужно какая-то библиотека для работы deepstack-ui? 

**Specified the IP address and port 80.**
Указал IP адрес и порт 80.  
![portainer 01](https://user-images.githubusercontent.com/64090632/116584515-19b0d900-a920-11eb-8d37-cdae3d8a26dd.jpg)
![portainer 02](https://user-images.githubusercontent.com/64090632/116584519-1c133300-a920-11eb-87b6-88ebe1e8823c.jpg)

-----------------

**Specified the IP address and port 8501.**
Указал IP адрес и порт 8501.  
![portainer 01-1](https://user-images.githubusercontent.com/64090632/116584666-42d16980-a920-11eb-9978-8d8f69d50609.jpg)
![portainer 02-2](https://user-images.githubusercontent.com/64090632/116584677-4533c380-a920-11eb-9c5a-3936adf38450.JPG)

**Comment by DivanX10** [comment]
**If you specify the external port 80, and the internal port 5000, as specified in your instructions. then I will get the following. In the beginning, there was an attempt to boot up, but then it gave an error about connecting and that's it, it can no longer connect**

Если указать внешний порт 80, а внутренний 5000, как указано в вашей инструкции. то получу следующее. В начале была попытка загрузиться, но потом выдало ошибку о подключении и все, больше не может подключиться

![portainer 06](https://user-images.githubusercontent.com/64090632/116587637-529e7d00-a923-11eb-8982-97a3373321b2.JPG)
![portainer 07](https://user-images.githubusercontent.com/64090632/116587640-53371380-a923-11eb-813f-982ff5a82263.JPG)
![portainer 08](https://user-images.githubusercontent.com/64090632/116588491-4f57c100-a924-11eb-95f1-d631a13aea0a.JPG)

**A message appeared in the logs**
В логах появилось сообщение
```
  You can now view your Streamlit app in your browser.
  Network URL: http://172.17.0.3:8501
  External URL: http://XX.XX.XX.XX:8501
  Stopping...
  A new version of Streamlit is available.
  See what's new at https://discuss.streamlit.io/c/announcements
  Enter the following command to upgrade:
  $ pip install streamlit --upgrade
  You can now view your Streamlit app in your browser.
  Network URL: http://172.17.0.3:8501
  External URL: http://XX.XX.XX.XX:8501
```

**Comment by DivanX10** [comment]
**I installed the robmarkcole/deepstack-ui image in Synology Docker and made the settings**
Установил в Synology Docker образ robmarkcole/deepstack-ui, сделал настройки
![synology -docker02](https://user-images.githubusercontent.com/64090632/116591054-1705b200-a927-11eb-86df-add726c61896.JPG)

**Installed pip install streamlit --upgrade**
Установил pip install streamlit --upgrade
![synology -docker](https://user-images.githubusercontent.com/64090632/116591137-2c7adc00-a927-11eb-9506-cb5cfa489699.JPG)


**And it worked, but it does not recognize the image and gives out about the expiration of time. I increased the time in DEEPSTACK_TIMEOUT to 60 seconds**
И заработало, но не распознает изображение и выдает об истечении времени. Я увеличил время в DEEPSTACK_TIMEOUT до 60 секунд 

![start_face_detection](https://user-images.githubusercontent.com/64090632/116592569-d149e900-a928-11eb-87a9-cf625aee3771.jpg)

![start_face_detection_bad](https://user-images.githubusercontent.com/64090632/116592605-dd35ab00-a928-11eb-8466-447ecd28ccd5.jpg)

**Comment by robmarkcole** [comment]
I would try running deepstack on another machine, synology may not be capable enough

**Comment by DivanX10** [comment]
**I tried it. Installed Debian 10 on the machine. Installed Docker. Installed Portainer. Downloaded the images. I get an error: Error from Deepstack request, status code: 403**
Попробовал. Установил на машину Debian 10. Установил Docker. Установил Portainer. Скачал образы. Получаю ошибку: Error from Deepstack request, status code: 403

![deepstack-ui status code portainer](https://user-images.githubusercontent.com/64090632/116690486-1a9a4700-a9c2-11eb-898b-c051b0e155e2.JPG)
![deepstack-ui status code 403](https://user-images.githubusercontent.com/64090632/116690491-1cfca100-a9c2-11eb-99c7-b17c5dc478cc.JPG)

**Also installed deepquestai/deepstack, the line /v1/vision/face/register does not appear either . I can't register the image. Try to raise it from 0 and if it works, then write down how you did it and I will repeat it. I put deepstack on Windows, it also does not work. It seems to me that the problem is in the deepstack itself.**
Также установил deepquestai/deepstack, тоже не появляется строка /v1/vision/face/register . Не могу зарегистрировать изображение. Попробуйте у себя поднять с 0 и если будет работать, то распишите как вы сделали и я повторю. Поставил deepstack на Windows, также не работает. Мне кажется, что все же проблема в самом deepstack.

**Comment by DivanX10** [comment]
**I found the reason why the Deepstack UI didn't work for me. It turns out that you had to specify the ip and port of the container where deepquestai/deepstack works, and I specified the ip and port to the internal container robmarkcole/deepstack-ui, so it did not work.**

Нашел причину, почему у меня не работал Deepstack UI. Оказывается нужно было указать ip и порт того контейнера, где работает deepquestai/deepstack, а я указывал ip и порт к внутреннему контейнеру robmarkcole/deepstack-ui, поэтому и не работало. 

**We configure it according to this scheme**
Настраиваем по такой схеме
![image](https://user-images.githubusercontent.com/64090632/117295374-6e9ea300-ae7c-11eb-92ed-52d54b6d52c6.png)

**Configuring the deepquestai/deepstack container itself**
Настраиваем сам контейнер deepquestai/deepstack
![image](https://user-images.githubusercontent.com/64090632/117295211-3bf4aa80-ae7c-11eb-8f1e-4d7c30805c1f.png)
![image](https://user-images.githubusercontent.com/64090632/117295438-85dd9080-ae7c-11eb-89e1-ce0973c5a079.png)

**This needs to be configured in the robmarkcole/deepstack-ui container**
Это нужно настроить в контейнере robmarkcole/deepstack-ui 
![image](https://user-images.githubusercontent.com/64090632/117295013-ffc14a00-ae7b-11eb-959a-b7580cddc83b.png)
![image](https://user-images.githubusercontent.com/64090632/117295047-0c45a280-ae7c-11eb-818f-7e368d5905e3.png)
