### ISSUE TITLE
Custom Model DeepStack_ActionNET

### ISSUE THREAD

**Issue by DivanX10** [robmarkcole/deepstack-ui#66]
About using custom model actionnetv2.pt through the integration of [HAS-Deep stack-object](https://github.com/robmarkcole/HASS-Deepstack-object) there are no examples of how it can be configured and there is no understanding of how it can be configured and whether it can be configured at all? Could you give examples of how to properly use deepstack-ui to add custom model actionnetv2.pt? About the full setup of the custom model actionnetv2.pt connection i wrote [here](https://community.home-assistant.io/t/face-and-person-detection-with-deepstack-local-and-free/92041/1311?u=divanx10). And in general, you can connect this [custom model actionnetv2.pt ](https://github.com/OlafenwaMoses/DeepStack_ActionNET), using your integration?

![image](https://user-images.githubusercontent.com/64090632/137949941-86c84eac-2381-479b-8255-438266e654c8.png)
![image](https://user-images.githubusercontent.com/64090632/137949883-5bdf8ee9-75ec-42ff-8a72-e8ac178f6ae4.png)
![image](https://user-images.githubusercontent.com/64090632/137949768-a6692850-0cc1-4079-be2f-350fd97b631c.png)

**Comment by robmarkcole** [comment]
use the arg `DEEPSTACK_CUSTOM_MODEL`

**Comment by DivanX10** [comment]
I don't understand you. Can you show by example how to set it all up correctly in the screenshots to make this custom model work?

![image|627x450](upload://vfMsM9w88n9zCwWatdjD9R9rWCr.png)
![image|480x500](upload://eT0oRTfYG1KjfpuBULCM6UQ4BGt.png)
