### ISSUE TITLE
Choose Internal IP 

### ISSUE THREAD

**Issue by vlar** [robmarkcole/deepstack-ui#67]
Hello, 

I'm running docker inside a proxmox contianer and upon pulling the deepstack-ui it picks up the internal IP of Proxmox and not the one of my local network. 

docker run -p 8501:8501 robmarkcole/deepstack-ui:latest

Is there any way to have it pick up another interface?

Here is my ip a

: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if17: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether fe:a3:6c:15:ab:88 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.21/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::fca3:6cff:fe15:ab88/64 scope link 
       valid_lft forever preferred_lft forever
3: br-53670cb1918f: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:43:3b:91:3d brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-53670cb1918f
       valid_lft forever preferred_lft forever
    inet6 fe80::42:43ff:fe3b:913d/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:45:fa:b8:fc brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:45ff:fefa:b8fc/64 scope link 
       valid_lft forever preferred_lft forever
6: veth6828f64@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-53670cb1918f state UP group default 
    link/ether a6:00:3a:b2:24:87 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::a400:3aff:feb2:2487/64 scope link 
       valid_lft forever preferred_lft forever
8: vethbc4cfe5@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 6e:3a:a4:b9:96:24 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::6c3a:a4ff:feb9:9624/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by robmarkcole** [comment]
use the `DEEPSTACK_IP` arg
