### ISSUE TITLE
multiple images of one face

### ISSUE THREAD

**Issue by bdydrp** [robmarkcole/deepstack-ui#71]
when registering face, do we still have to have each photo of the same person a unique name?
Photo Person A = Person A
Photo Person A-1 = Person A-1
Photo Person A-2 = Person A-2
Etc etc??

Doing it this way, it seems to not register some of the images to a person.
When i do Face Rec of Person A-2, i get Person A-1 @60% instead of Person A-2 @100%

Thanks

**Comment by robmarkcole** [comment]
you should use the same name. Not sure I answered this but you can raise on the deepstack forum. Cheers
