### ISSUE TITLE
Deepstack connection error with docker win 10

### ISSUE THREAD

**Issue by xcellenceit** [robmarkcole/deepstack-ui#72]
Hi, New to this...

I am following this article https://medium.com/deepquestai/deepstack-ui-object-detection-with-zero-code-e4e6f1bf8ba4

DeepStack is running successfully inside docker on windows 10, at localhost:80. I am running deepstack-ui utilizing the command with deepstack on localhost exactly same as described in above article, again on same win 10 PC docker.

I am unable to use deeepstack-ui and getting following error:

DeepstackException: Deepstack connection error, check your IP and port: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /v1/vision/detection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff13ded71f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

Any idea what could be wrong? And how to resolve it?

**Comment by robmarkcole** [comment]
for host try the ip address of the machine

**Comment by xcellenceit** [comment]
thank you for such a quick response... didn't expected it so fast.

Changing from localhost to IP did resolved the issue. Thanks
